export const sizingVariables = {
    '--border-radius': '3px',
    '--line-normal': '3px',
    '--outline-size': '3px',
    '--spacing-normal': '3px',
    '--site-container-min-size': '1150px',
    '--site-container-max-size': '1400px',
    '--site-container-padding': '20px',
    '--two-pane-left-width': '550px',
    '--search-button-size': '36px',
    '--stepper-button-size': '24px',
    '--line-medium': 'calc(var(--line-normal) * 1.5px)',
    '--line-thick': 'calc(var(--line-normal) * 2px)',
    '--spacing-2x': 'calc(var(--spacing-normal) * 2px)',
    '--spacing-3x': 'calc(var(--spacing-normal) * 3px)',
    '--spacing-4x': 'calc(var(--spacing-normal) * 4px)',
    '--spacing-5x': 'calc(var(--spacing-normal) * 5px)',
    '--margin': 'calc(var(--spacing-normal) * 0.5px)',
};
