export const typographyVariables = {
    '--font-size-base': '14px',
    '--font-size-x-small': '10px',
    '--font-size-small': '12px',
    '--font-size-normal': '14px',
    '--font-size-large': '16.8px',
    '--h1-font-size': '24px',
    '--h2-font-size': '18px',
    '--h3-font-size': '16px',
    '--h4-font-size': '14px',
    '--h5-font-size': '12px',
    '--h6-font-size': '10px',
    '--font-family-primary': '-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Droid Sans, Helvetica Neue, sans-serif',
    '--font-family-secondary': '-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Droid Sans, Helvetica Neue, sans-serif',
    '--font-weight-light': '200',
    '--font-weight-normal': '400',
    '--font-weight-medium': '500',
    '--font-weight-bold': '600',
    '--link-decoration-normal': 'none',
    '--link-decoration-hover': 'underline',
    '--line-height-x-small': 'calc(var(--font-size-x-small) * 1.4px)',
    '--line-height-small': 'calc(var(--font-size-small) * 1.4px)',
    '--line-height-normal': 'calc(var(--font-size-normal) * 1.4px)',
    '--line-height-large': 'calc(var(--font-size-large) * 1.4px)',
    '--heading-font-family': 'var(--font-family-secondary)',
    '--heading-font-weight': 'var(--font-weight-bold)',
};
