export const sizingVariables = {
    '--border-radius': '3px',
    '--line-normal': '3px',
    '--space-0': '0px',
    '--space-25': '2px',
    '--site-container-min-size': '1150px',
    '--site-container-max-size': '1400px',
    '--site-container-padding': '20px',
    '--two-pane-left-width': '550px',
    '--search-button-size': '36px',
    '--stepper-button-size': '24px',
    '--space-50': 'calc(var(--space-25) * 2px)',
    '--space-75': 'calc(var(--space-50) * 3px)',
    '--space-100': 'calc(var(--space-25) * 4px)',
    // FIXME: Temporary fix, till we decide how we should proceed
    '--space-125': 'calc(var(--space-25) * 5px)',
    '--space-150': 'calc(var(--space-25) * 6px)',
    '--space-200': 'calc(var(--space-25) * 8px)',
    '--space-250': 'calc(var(--space-25) * 10px)',
    '--space-300': 'calc(var(--space-25) * 12px)',
    '--space-400': 'calc(var(--space-25) * 16px)',
    '--space-500': 'calc(var(--space-25) * 20px)',
    '--space-600': 'calc(var(--space-25) * 24px)',
    '--space-800': 'calc(var(--space-25) * 32px)',
    '--space-1000': 'calc(var(--space-25) * 40px)',
    '--margin': 'calc(var(--space-50) * 0.5px)',
};
