export const typographyVariables = {
    '--font-size-base': '16px',
    '--font-size-x-small': '12px',
    '--font-size-small': '14px',
    '--font-size-normal': '16px',
    '--font-size-large': '18px',
    '--h1-font-size': '28px',
    '--h2-font-size': '24px',
    '--h3-font-size': '20px',
    '--h4-font-size': '18px',
    '--h5-font-size': '16px',
    '--h6-font-size': '14px',
    '--font-family-primary': 'Noto Sans, Noto Sans JP, Noto Sans SC, Noto Sans Hebrew, sans-serif',
    '--font-weight-normal': '400',
    '--font-weight-bold': '600',
    '--link-decoration-normal': 'underline',
    '--link-decoration-hover': 'underline',
    '--line-height-x-small': '16px',
    '--line-height-small': '20px',
    '--line-height-normal': '24px',
    '--line-height-large': '28px',
    '--line-height-x-large': '32px',
    '--heading-font-family': 'var(--font-family-primary)',
    '--heading-font-weight': 'var(--font-weight-bold)',
};
